/* Generated by the Nim Compiler v2.1.1 */
var framePtr = null;
var excHandler = 0;
var lastJSError = null;
var NTI134217745 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555169 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217746 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217749 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217751 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33554435 = {size: 0,kind: 31,base: null,node: null,finalizer: null};
var NTI33555820 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI33555163 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555171 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33554449 = {size: 0,kind: 28,base: null,node: null,finalizer: null};
var NTI33554450 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI33555170 = {size: 0, kind: 22, base: null, node: null, finalizer: null};
var NTI33555167 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI33555168 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217741 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NTI134217743 = {size: 0, kind: 17, base: null, node: null, finalizer: null};
var NNI134217743 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217743.node = NNI134217743;
var NNI134217741 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217741.node = NNI134217741;
var NNI33555168 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555168.node = NNI33555168;
NTI33555170.base = NTI33555167;
NTI33555171.base = NTI33555167;
var NNI33555167 = {kind: 2, len: 5, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "parent", len: 0, typ: NTI33555170, name: "parent", sons: null}, 
{kind: 1, offset: "name", len: 0, typ: NTI33554450, name: "name", sons: null}, 
{kind: 1, offset: "message", len: 0, typ: NTI33554449, name: "msg", sons: null}, 
{kind: 1, offset: "trace", len: 0, typ: NTI33554449, name: "trace", sons: null}, 
{kind: 1, offset: "up", len: 0, typ: NTI33555171, name: "up", sons: null}]};
NTI33555167.node = NNI33555167;
var NNI33555163 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555163.node = NNI33555163;
NTI33555167.base = NTI33555163;
NTI33555168.base = NTI33555167;
NTI134217741.base = NTI33555168;
NTI134217743.base = NTI134217741;
var NNI33555820 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "Field0", len: 0, typ: NTI33554450, name: "Field0", sons: null}, 
{kind: 1, offset: "Field1", len: 0, typ: NTI33554435, name: "Field1", sons: null}, 
{kind: 1, offset: "Field2", len: 0, typ: NTI33554450, name: "Field2", sons: null}]};
NTI33555820.node = NNI33555820;
var NNI134217751 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217751.node = NNI134217751;
NTI134217751.base = NTI33555168;
var NNI134217749 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217749.node = NNI134217749;
NTI134217749.base = NTI33555168;
var NNI134217746 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217746.node = NNI134217746;
var NNI33555169 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI33555169.node = NNI33555169;
NTI33555169.base = NTI33555167;
NTI134217746.base = NTI33555169;
var NNI134217745 = {kind: 2, len: 0, offset: 0, typ: null, name: null, sons: []};
NTI134217745.node = NNI134217745;
NTI134217745.base = NTI33555168;

function mnewString(len_p0) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; i++) {result[i] = 0;}
    return result;
  

  
}

function arrayConstr(len_p0, value_p1, typ_p2) {
        var result = new Array(len_p0);
    for (var i = 0; i < len_p0; ++i) result[i] = nimCopy(null, value_p1, typ_p2);
    return result;
  

  
}

function setConstr() {
        var result = {};
    for (var i = 0; i < arguments.length; ++i) {
      var x = arguments[i];
      if (typeof(x) == "object") {
        for (var j = x[0]; j <= x[1]; ++j) {
          result[j] = true;
        }
      } else {
        result[x] = true;
      }
    }
    return result;
  

  
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_p0, src_p1, ti_p2) {
  var result_33557263 = null;

    switch (ti_p2.kind) {
    case 21:
    case 22:
    case 23:
    case 5:
      if (!(isFatPointer__system_u2811(ti_p2))) {
      result_33557263 = src_p1;
      }
      else {
        result_33557263 = [src_p1[0], src_p1[1]];
      }
      
      break;
    case 19:
            if (dest_p0 === null || dest_p0 === undefined) {
        dest_p0 = {};
      }
      else {
        for (var key in dest_p0) { delete dest_p0[key]; }
      }
      for (var key in src_p1) { dest_p0[key] = src_p1[key]; }
      result_33557263 = dest_p0;
    
      break;
    case 18:
    case 17:
      if (!((ti_p2.base == null))) {
      result_33557263 = nimCopy(dest_p0, src_p1, ti_p2.base);
      }
      else {
      if ((ti_p2.kind == 17)) {
      result_33557263 = (dest_p0 === null || dest_p0 === undefined) ? {m_type: ti_p2} : dest_p0;
      }
      else {
        result_33557263 = (dest_p0 === null || dest_p0 === undefined) ? {} : dest_p0;
      }
      }
      nimCopyAux(result_33557263, src_p1, ti_p2.node);
      break;
    case 4:
    case 16:
            if(ArrayBuffer.isView(src_p1)) { 
        if(dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new src_p1.constructor(src_p1);
        } else {
          dest_p0.set(src_p1, 0);
        }
        result_33557263 = dest_p0;
      } else {
        if (src_p1 === null) {
          result_33557263 = null;
        }
        else {
          if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
            dest_p0 = new Array(src_p1.length);
          }
          result_33557263 = dest_p0;
          for (var i = 0; i < src_p1.length; ++i) {
            result_33557263[i] = nimCopy(result_33557263[i], src_p1[i], ti_p2.base);
          }
        }
      }
    
      break;
    case 24:
    case 27:
            if (src_p1 === null) {
        result_33557263 = null;
      }
      else {
        if (dest_p0 === null || dest_p0 === undefined || dest_p0.length != src_p1.length) {
          dest_p0 = new Array(src_p1.length);
        }
        result_33557263 = dest_p0;
        for (var i = 0; i < src_p1.length; ++i) {
          result_33557263[i] = nimCopy(result_33557263[i], src_p1[i], ti_p2.base);
        }
      }
    
      break;
    case 28:
            if (src_p1 !== null) {
        result_33557263 = src_p1.slice(0);
      }
    
      break;
    default: 
      result_33557263 = src_p1;
      break;
    }

  return result_33557263;

}

function cstrToNimstr(c_p0) {
      var ln = c_p0.length;
  var result = new Array(ln);
  var r = 0;
  for (var i = 0; i < ln; ++i) {
    var ch = c_p0.charCodeAt(i);

    if (ch < 128) {
      result[r] = ch;
    }
    else {
      if (ch < 2048) {
        result[r] = (ch >> 6) | 192;
      }
      else {
        if (ch < 55296 || ch >= 57344) {
          result[r] = (ch >> 12) | 224;
        }
        else {
            ++i;
            ch = 65536 + (((ch & 1023) << 10) | (c_p0.charCodeAt(i) & 1023));
            result[r] = (ch >> 18) | 240;
            ++r;
            result[r] = ((ch >> 12) & 63) | 128;
        }
        ++r;
        result[r] = ((ch >> 6) & 63) | 128;
      }
      ++r;
      result[r] = (ch & 63) | 128;
    }
    ++r;
  }
  return result;
  

  
}

function toJSStr(s_p0) {
  var result_33556889 = null;

    var res_33556930 = newSeq__system_u2474((s_p0).length);
    var i_33556931 = 0;
    var j_33556932 = 0;
    Label1: {
        Label2: while (true) {
        if (!(i_33556931 < (s_p0).length)) break Label2;
          var c_33556933 = s_p0[i_33556931];
          if ((c_33556933 < 128)) {
          res_33556930[j_33556932] = String.fromCharCode(c_33556933);
          i_33556931 += 1;
          }
          else {
            var helper_33556945 = newSeq__system_u2474(0);
            Label3: {
                Label4: while (true) {
                if (!true) break Label4;
                  var code_33556946 = c_33556933.toString(16);
                  if ((((code_33556946) == null ? 0 : (code_33556946).length) == 1)) {
                  helper_33556945.push("%0");;
                  }
                  else {
                  helper_33556945.push("%");;
                  }
                  
                  helper_33556945.push(code_33556946);;
                  i_33556931 += 1;
                  if ((((s_p0).length <= i_33556931) || (s_p0[i_33556931] < 128))) {
                  break Label3;
                  }
                  
                  c_33556933 = s_p0[i_33556931];
                }
            };
++excHandler;
            try {
            res_33556930[j_33556932] = decodeURIComponent(helper_33556945.join(""));
--excHandler;
} catch (EXCEPTION) {
 var prevJSError = lastJSError;
 lastJSError = EXCEPTION;
 --excHandler;
            res_33556930[j_33556932] = helper_33556945.join("");
            lastJSError = prevJSError;
            } finally {
            }
          }
          
          j_33556932 += 1;
        }
    };
    if (res_33556930.length < j_33556932) { for (var i = res_33556930.length ; i < j_33556932 ; ++i) res_33556930.push(null); }
               else { res_33556930.length = j_33556932; };
    result_33556889 = res_33556930.join("");

  return result_33556889;

}

function raiseException(e_p0, ename_p1) {
    e_p0.name = ename_p1;
    if ((excHandler == 0)) {
    unhandledException(e_p0);
    }
    
    e_p0.trace = nimCopy(null, rawWriteStackTrace__system_u2159(), NTI33554449);
    throw e_p0;

  
}

function addInt(a_p0, b_p1) {
        var result = a_p0 + b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function chckRange(i_p0, a_p1, b_p2) {
  var result_33557311 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557311 = i_p0;
    break BeforeRet;
    }
    else {
    raiseRangeError();
    }
    
  };

  return result_33557311;

}

function chckIndx(i_p0, a_p1, b_p2) {
  var result_33557306 = 0;

  BeforeRet: {
    if (((a_p1 <= i_p0) && (i_p0 <= b_p2))) {
    result_33557306 = i_p0;
    break BeforeRet;
    }
    else {
    raiseIndexError(i_p0, a_p1, b_p2);
    }
    
  };

  return result_33557306;

}

function mulInt(a_p0, b_p1) {
        var result = a_p0 * b_p1;
    checkOverflowInt(result);
    return result;
  

  
}

function makeNimstrLit(c_p0) {
      var result = [];
  for (var i = 0; i < c_p0.length; ++i) {
    result[i] = c_p0.charCodeAt(i);
  }
  return result;
  

  
}

function subInt(a_p0, b_p1) {
        var result = a_p0 - b_p1;
    checkOverflowInt(result);
    return result;
  

  
}
var F = {procname: "module macros", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module macros", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/core/macros.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsbigints", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/jsbigints.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/jsutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/hashes.nim", line: 0};
framePtr = F;
F.line = 218;
F.filename = "hashes.nim";
var objectID_738197679 = [0];
framePtr = F.prev;
var F = {procname: "module hashes", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/hashes.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops_utils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/bitops_utils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module countbits_impl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/countbits_impl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module bitops", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/bitops.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module fenv", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/fenv.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module math", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/math.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module algorithm", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/algorithm.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module outparams", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/outparams.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module tables", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/collections/tables.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsffi.nim", line: 0};
framePtr = F;
F.line = 45;
F.filename = "jsffi.nim";
F.line = 46;
framePtr = F.prev;
var F = {procname: "module jsffi", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/jsffi.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/asyncjs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/asyncjs.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module underscored_calls", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/underscored_calls.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module underscored_calls", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/underscored_calls.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sugar", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/sugar.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module sugar", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/sugar.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs_examples_1", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_1.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module parseutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/parseutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module typetraits", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/typetraits.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module enumutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/enumutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strbasics", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/strbasics.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module unicode", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/unicode.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strimpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/strimpl.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module strutils", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
framePtr = F;
framePtr = F.prev;

function catch__asyncjs95examples9550_u55(future_p0, onReject_p1) {
  var result_973078587 = null;

  var F = {procname: "catch.catch", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/js/asyncjs.nim", line: 0};
  framePtr = F;
    F.line = 269;
    F.filename = "asyncjs.nim";
    result_973078587 = future_p0.catch(onReject_p1)
  framePtr = F.prev;

  return result_973078587;

}

function add__system_u1931(x_p0, x_p0_Idx, y_p1) {
          if (x_p0[x_p0_Idx] === null) { x_p0[x_p0_Idx] = []; }
      var off = x_p0[x_p0_Idx].length;
      x_p0[x_p0_Idx].length += y_p1.length;
      for (var i = 0; i < y_p1.length; ++i) {
        x_p0[x_p0_Idx][off+i] = y_p1.charCodeAt(i);
      }
    

  
}

function isFatPointer__system_u2811(ti_p0) {
  var result_33557245 = false;

  BeforeRet: {
    result_33557245 = !((ConstSet1[ti_p0.base.kind] != undefined));
    break BeforeRet;
  };

  return result_33557245;

}

function nimCopyAux(dest_p0, src_p1, n_p2) {
    switch (n_p2.kind) {
    case 0:
      break;
    case 1:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
    
      break;
    case 2:
          for (var i = 0; i < n_p2.sons.length; i++) {
      nimCopyAux(dest_p0, src_p1, n_p2.sons[i]);
    }
    
      break;
    case 3:
            dest_p0[n_p2.offset] = nimCopy(dest_p0[n_p2.offset], src_p1[n_p2.offset], n_p2.typ);
      for (var i = 0; i < n_p2.sons.length; ++i) {
        nimCopyAux(dest_p0, src_p1, n_p2.sons[i][1]);
      }
    
      break;
    }

  
}

function auxWriteStackTrace__system_u2066(f_p0) {
  var result_33556500 = [[]];

    var it_33556508 = f_p0;
    var i_33556509 = 0;
    var total_33556510 = 0;
    var tempFrames_33556511 = arrayConstr(64, {Field0: null, Field1: 0, Field2: null}, NTI33555820);
    Label1: {
        Label2: while (true) {
        if (!(!((it_33556508 == null)) && (i_33556509 <= 63))) break Label2;
          tempFrames_33556511[i_33556509].Field0 = it_33556508.procname;
          tempFrames_33556511[i_33556509].Field1 = it_33556508.line;
          tempFrames_33556511[i_33556509].Field2 = it_33556508.filename;
          i_33556509 += 1;
          total_33556510 += 1;
          it_33556508 = it_33556508.prev;
        }
    };
    Label3: {
        Label4: while (true) {
        if (!!((it_33556508 == null))) break Label4;
          total_33556510 += 1;
          it_33556508 = it_33556508.prev;
        }
    };
    result_33556500[0] = nimCopy(null, [], NTI33554449);
    if (!((total_33556510 == i_33556509))) {
    result_33556500[0].push.apply(result_33556500[0], [40]);;
    result_33556500[0].push.apply(result_33556500[0], HEX24__systemZdollars_u8((total_33556510 - i_33556509)));;
    result_33556500[0].push.apply(result_33556500[0], [32,99,97,108,108,115,32,111,109,105,116,116,101,100,41,32,46,46,46,10]);;
    }
    
    Label5: {
      var j_33556541 = 0;
      var colontmp__973078636 = 0;
      colontmp__973078636 = (i_33556509 - 1);
      var res_973078638 = colontmp__973078636;
      Label6: {
          Label7: while (true) {
          if (!(0 <= res_973078638)) break Label7;
            j_33556541 = res_973078638;
            result_33556500[0].push.apply(result_33556500[0], cstrToNimstr(tempFrames_33556511[j_33556541].Field2));;
            if ((0 < tempFrames_33556511[j_33556541].Field1)) {
            result_33556500[0].push.apply(result_33556500[0], [40]);;
            addInt__stdZprivateZdigitsutils_u238(result_33556500, 0, tempFrames_33556511[j_33556541].Field1);
            if (false) {
            result_33556500[0].push.apply(result_33556500[0], [44,32]);;
            addInt__stdZprivateZdigitsutils_u238(result_33556500, 0, 0);
            }
            
            result_33556500[0].push.apply(result_33556500[0], [41]);;
            }
            
            result_33556500[0].push.apply(result_33556500[0], [32,97,116,32]);;
            add__system_u1931(result_33556500, 0, tempFrames_33556511[j_33556541].Field0);
            result_33556500[0].push.apply(result_33556500[0], [10]);;
            res_973078638 -= 1;
          }
      };
    };

  return result_33556500[0];

}

function rawWriteStackTrace__system_u2159() {
  var result_33556592 = [];

    if (!((framePtr == null))) {
    result_33556592 = nimCopy(null, ([84,114,97,99,101,98,97,99,107,32,40,109,111,115,116,32,114,101,99,101,110,116,32,99,97,108,108,32,108,97,115,116,41,10] || []).concat(auxWriteStackTrace__system_u2066(framePtr) || []), NTI33554449);
    }
    else {
      result_33556592 = nimCopy(null, [78,111,32,115,116,97,99,107,32,116,114,97,99,101,98,97,99,107,32,97,118,97,105,108,97,98,108,101,10], NTI33554449);
    }
    

  return result_33556592;

}

function newSeq__system_u2474(len_p0) {
  var result_33556909 = [];

  var F = {procname: "newSeq.newSeq", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system.nim", line: 0};
  framePtr = F;
    F.line = 633;
    F.filename = "system.nim";
    result_33556909 = new Array(len_p0); for (var i = 0 ; i < len_p0 ; ++i) { result_33556909[i] = null; }  framePtr = F.prev;

  return result_33556909;

}

function unhandledException(e_p0) {
    var buf_33556637 = [[]];
    if (!(((e_p0.message).length == 0))) {
    buf_33556637[0].push.apply(buf_33556637[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110,58,32]);;
    buf_33556637[0].push.apply(buf_33556637[0], e_p0.message);;
    }
    else {
    buf_33556637[0].push.apply(buf_33556637[0], [69,114,114,111,114,58,32,117,110,104,97,110,100,108,101,100,32,101,120,99,101,112,116,105,111,110]);;
    }
    
    buf_33556637[0].push.apply(buf_33556637[0], [32,91]);;
    add__system_u1931(buf_33556637, 0, e_p0.name);
    buf_33556637[0].push.apply(buf_33556637[0], [93,10]);;
    buf_33556637[0].push.apply(buf_33556637[0], rawWriteStackTrace__system_u2159());;
    var cbuf_33556638 = toJSStr(buf_33556637[0]);
    framePtr = null;
      if (typeof(Error) !== "undefined") {
    throw new Error(cbuf_33556638);
  }
  else {
    throw cbuf_33556638;
  }
  

  
}

function raiseOverflow() {
    raiseException({message: [111,118,101,114,45,32,111,114,32,117,110,100,101,114,102,108,111,119], parent: null, m_type: NTI134217743, name: null, trace: [], up: null}, "OverflowDefect");

  
}

function checkOverflowInt(a_p0) {
        if (a_p0 > 2147483647 || a_p0 < -2147483648) raiseOverflow();
  

  
}

function raiseRangeError() {
    raiseException({message: [118,97,108,117,101,32,111,117,116,32,111,102,32,114,97,110,103,101], parent: null, m_type: NTI134217751, name: null, trace: [], up: null}, "RangeDefect");

  
}

function raiseIndexError(i_p0, a_p1, b_p2) {
    var Temporary1;

    if ((b_p2 < a_p1)) {
    Temporary1 = [105,110,100,101,120,32,111,117,116,32,111,102,32,98,111,117,110,100,115,44,32,116,104,101,32,99,111,110,116,97,105,110,101,114,32,105,115,32,101,109,112,116,121];
    }
    else {
    Temporary1 = ([105,110,100,101,120,32] || []).concat(HEX24__systemZdollars_u8(i_p0) || [],[32,110,111,116,32,105,110,32] || [],HEX24__systemZdollars_u8(a_p1) || [],[32,46,46,32] || [],HEX24__systemZdollars_u8(b_p2) || []);
    }
    
    raiseException({message: nimCopy(null, Temporary1, NTI33554449), parent: null, m_type: NTI134217749, name: null, trace: [], up: null}, "IndexDefect");

  
}

function addChars__stdZprivateZdigitsutils_u199(result_p0, result_p0_Idx, x_p1, start_p2, n_p3) {
    var Temporary1;

  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 44;
    F.filename = "digitsutils.nim";
    var old_301990093 = (result_p0[result_p0_Idx]).length;
    F.line = 45;
    if (result_p0[result_p0_Idx].length < (Temporary1 = chckRange(addInt(old_301990093, n_p3), 0, 2147483647), Temporary1)) { for (var i = result_p0[result_p0_Idx].length; i < Temporary1; ++i) result_p0[result_p0_Idx].push(0); }
         else {result_p0[result_p0_Idx].length = Temporary1; };
    Label2: {
      F.line = 47;
      var iHEX60gensym4_301990107 = 0;
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_973078631 = 0;
      Label3: {
        F.line = 129;
          Label4: while (true) {
          if (!(i_973078631 < n_p3)) break Label4;
            F.line = 50;
            F.filename = "digitsutils.nim";
            iHEX60gensym4_301990107 = i_973078631;
            F.line = 50;
            result_p0[result_p0_Idx][chckIndx(addInt(old_301990093, iHEX60gensym4_301990107), 0, (result_p0[result_p0_Idx]).length - 1)] = x_p1.charCodeAt(chckIndx(addInt(start_p2, iHEX60gensym4_301990107), 0, (x_p1).length - 1));
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_973078631 = addInt(i_973078631, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function addChars__stdZprivateZdigitsutils_u195(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "addChars.addChars", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 56;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u199(result_p0, result_p0_Idx, x_p1, 0, ((x_p1) == null ? 0 : (x_p1).length));
  framePtr = F.prev;

  
}

function addInt__stdZprivateZdigitsutils_u220(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 112;
    F.filename = "digitsutils.nim";
    addChars__stdZprivateZdigitsutils_u195(result_p0, result_p0_Idx, ((x_p1) + ""));
  framePtr = F.prev;

  
}

function addInt__stdZprivateZdigitsutils_u238(result_p0, result_p0_Idx, x_p1) {
  var F = {procname: "digitsutils.addInt", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/private/digitsutils.nim", line: 0};
  framePtr = F;
    F.line = 116;
    F.filename = "digitsutils.nim";
    addInt__stdZprivateZdigitsutils_u220(result_p0, result_p0_Idx, BigInt(x_p1));
  framePtr = F.prev;

  
}

function HEX24__systemZdollars_u8(x_p0) {
  var result_369098762 = [[]];

  var F = {procname: "dollars.$", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/dollars.nim", line: 0};
  framePtr = F;
    F.line = 18;
    F.filename = "dollars.nim";
    addInt__stdZprivateZdigitsutils_u238(result_369098762, 0, x_p0);
  framePtr = F.prev;

  return result_369098762[0];

}
async function fn__asyncjs95examples9550_u8(n_p0) {
  var result_973078539 = null;

  var F = {procname: "asyncjs_examples_2.fn", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
  framePtr = F;
    if ((7 <= n_p0)) {
    F.line = 251;
    F.filename = "asyncjs.nim";
    raiseException({message: ([102,111,111,98,97,114,58,32] || []).concat(HEX24__systemZdollars_u8(n_p0) || []), parent: null, m_type: NTI134217746, name: null, trace: [], up: null}, "ValueError");
    }
    else {
      F.line = 251;
      result_973078539 = mulInt(n_p0, 2);
    }
    
  framePtr = F.prev;

  return result_973078539;

}

function sysFatal__stdZassertions_u45(message_p1) {
  var F = {procname: "sysFatal.sysFatal", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/system/fatal.nim", line: 0};
  framePtr = F;
    F.line = 53;
    F.filename = "fatal.nim";
    raiseException({message: nimCopy(null, message_p1, NTI33554449), m_type: NTI134217745, parent: null, name: null, trace: [], up: null}, "AssertionDefect");
  framePtr = F.prev;

  
}

function raiseAssert__stdZassertions_u43(msg_p0) {
  var F = {procname: "assertions.raiseAssert", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 36;
    F.filename = "assertions.nim";
    sysFatal__stdZassertions_u45(msg_p0);
  framePtr = F.prev;

  
}

function failedAssertImpl__stdZassertions_u85(msg_p0) {
  var F = {procname: "assertions.failedAssertImpl", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/std/assertions.nim", line: 0};
  framePtr = F;
    F.line = 41;
    F.filename = "assertions.nim";
    raiseAssert__stdZassertions_u43(msg_p0);
  framePtr = F.prev;

  
}

function nsuFindChar(s_p0, sub_p1, start_p2, last_p3) {
    var Temporary1;

  var result_989857388 = 0;

  var F = {procname: "strutils.find", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 2009;
    F.filename = "strutils.nim";
    result_989857388 = (-1);
    F.line = 2010;
    if ((last_p3 < 0)) {
    Temporary1 = (s_p0).length - 1;
    }
    else {
    Temporary1 = last_p3;
    }
    
    var last_989857389 = Temporary1;
    Label2: {
      F.line = 2013;
      var iHEX60gensym177_989857403 = 0;
      F.line = 81;
      F.filename = "iterators_1.nim";
      var colontmp__973078647 = 0;
      F.line = 2013;
      F.filename = "strutils.nim";
      colontmp__973078647 = start_p2;
      F.line = 96;
      F.filename = "iterators_1.nim";
      var res_973078648 = colontmp__973078647;
      Label3: {
        F.line = 97;
          Label4: while (true) {
          if (!(res_973078648 <= last_989857389)) break Label4;
            F.line = 2027;
            F.filename = "strutils.nim";
            iHEX60gensym177_989857403 = res_973078648;
            if ((s_p0[chckIndx(iHEX60gensym177_989857403, 0, (s_p0).length - 1)] == sub_p1)) {
            F.line = 2015;
            result_989857388 = iHEX60gensym177_989857403;
            break BeforeRet;
            }
            
            F.line = 102;
            F.filename = "iterators_1.nim";
            res_973078648 = addInt(res_973078648, 1);
          }
      };
    };
  };
  framePtr = F.prev;

  return result_989857388;

}

function nsuFindStrA(a_p0, s_p1, sub_p2, start_p3, last_p4) {
    var Temporary1;

  var result_989857369 = 0;

  var F = {procname: "strutils.find", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 1969;
    F.filename = "strutils.nim";
    if ((last_p4 < 0)) {
    Temporary1 = (s_p1).length - 1;
    }
    else {
    Temporary1 = last_p4;
    }
    
    var last_989857370 = Temporary1;
    F.line = 1970;
    var subLast_989857371 = subInt((sub_p2).length, 1);
    if ((subLast_989857371 == (-1))) {
    F.line = 1975;
    result_989857369 = start_p3;
    break BeforeRet;
    }
    
    F.line = 1979;
    result_989857369 = (-1);
    F.line = 1980;
    var skip_989857372 = start_p3;
    Label2: {
      F.line = 1982;
        Label3: while (true) {
        if (!(subLast_989857371 <= subInt(last_989857370, skip_989857372))) break Label3;
          F.line = 1983;
          var i_989857373 = subLast_989857371;
          Label4: {
            F.line = 1984;
              Label5: while (true) {
              if (!(s_p1[chckIndx(addInt(skip_989857372, i_989857373), 0, (s_p1).length - 1)] == sub_p2[chckIndx(i_989857373, 0, (sub_p2).length - 1)])) break Label5;
                if ((i_989857373 == 0)) {
                F.line = 1986;
                result_989857369 = skip_989857372;
                break BeforeRet;
                }
                
                F.line = 1987;
                i_989857373 = subInt(i_989857373, 1);
              }
          };
          F.line = 1988;
          skip_989857372 = addInt(skip_989857372, a_p0[chckIndx(s_p1[chckIndx(addInt(skip_989857372, subLast_989857371), 0, (s_p1).length - 1)], 0, (a_p0).length - 1)]);
        }
    };
  };
  framePtr = F.prev;

  return result_989857369;

}

function fill__pureZstrutils_u1566(a_p0, value_p1) {
  var F = {procname: "fill.fill", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/algorithm.nim", line: 0};
  framePtr = F;
    F.line = 72;
    F.filename = "algorithm.nim";
    var xHEX60gensym173_989857319 = 0;
    Label1: {
      F.line = 98;
        Label2: while (true) {
        if (!(xHEX60gensym173_989857319 <= (a_p0).length - 1)) break Label2;
          F.line = 98;
          a_p0[chckIndx(xHEX60gensym173_989857319, 0, (a_p0).length - 1)] = value_p1;
          F.line = 75;
          xHEX60gensym173_989857319 = addInt(xHEX60gensym173_989857319, 1);
        }
    };
  framePtr = F.prev;

  
}

function nsuInitSkipTable(a_p0, sub_p1) {
  var F = {procname: "strutils.initSkipTable", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 1942;
    F.filename = "strutils.nim";
    var m_989857309 = (sub_p1).length;
    F.line = 1943;
    fill__pureZstrutils_u1566(a_p0, m_989857309);
    Label1: {
      F.line = 1945;
      var i_989857328 = 0;
      F.line = 126;
      F.filename = "iterators_1.nim";
      var colontmp__973078653 = 0;
      F.line = 1945;
      F.filename = "strutils.nim";
      colontmp__973078653 = subInt(m_989857309, 1);
      F.line = 128;
      F.filename = "iterators_1.nim";
      var i_973078654 = 0;
      Label2: {
        F.line = 129;
          Label3: while (true) {
          if (!(i_973078654 < colontmp__973078653)) break Label3;
            F.line = 1945;
            F.filename = "strutils.nim";
            i_989857328 = i_973078654;
            F.line = 1945;
            a_p0[chckIndx(sub_p1[chckIndx(i_989857328, 0, (sub_p1).length - 1)], 0, (a_p0).length - 1)] = subInt(subInt(m_989857309, 1), i_989857328);
            F.line = 131;
            F.filename = "iterators_1.nim";
            i_973078654 = addInt(i_973078654, 1);
          }
      };
    };
  framePtr = F.prev;

  
}

function nsuInitNewSkipTable(sub_p0) {
  var result_989857362 = [new Int32Array(256)];

  var F = {procname: "strutils.initSkipTable", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
    F.line = 1955;
    F.filename = "strutils.nim";
    nsuInitSkipTable(result_989857362[0], sub_p0);
  framePtr = F.prev;

  return result_989857362[0];

}

function nsuFindStr(s_p0, sub_p1, start_p2, last_p3) {
  var result_989857425 = 0;

  var F = {procname: "strutils.find", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    if ((subInt((s_p0).length, start_p2) < (sub_p1).length)) {
    F.line = 2067;
    F.filename = "strutils.nim";
    result_989857425 = (-1);
    break BeforeRet;
    }
    
    if (((sub_p1).length == 1)) {
    F.line = 2068;
    result_989857425 = nsuFindChar(s_p0, sub_p1[chckIndx(0, 0, (sub_p1).length - 1)], start_p2, last_p3);
    break BeforeRet;
    }
    
    F.line = 2071;
    result_989857425 = nsuFindStrA(nsuInitNewSkipTable(sub_p1), s_p0, sub_p1, start_p2, last_p3);
  };
  framePtr = F.prev;

  return result_989857425;

}

function contains__pureZstrutils_u1811(s_p0, sub_p1) {
  var result_989857558 = false;

  var F = {procname: "strutils.contains", prev: framePtr, filename: "/home/runner/work/Nim/Nim/lib/pure/strutils.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 2225;
    F.filename = "strutils.nim";
    result_989857558 = (0 <= nsuFindStr(s_p0, sub_p1, 0, (-1)));
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_989857558;

}
async function main__asyncjs95examples9550_u26() {
    
function HEX3Aanonymous__asyncjs95examples9550_u36(r_p0) {
      var F = {procname: "main.:anonymous", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
      framePtr = F;
        F.line = 251;
        F.filename = "asyncjs.nim";
        reason_973078562 = r_p0;
      framePtr = F.prev;

      
    }
    
function HEX3Aanonymous__asyncjs95examples9550_u74(r_p0) {
      var F = {procname: "main.:anonymous", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
      framePtr = F;
        F.line = 251;
        F.filename = "asyncjs.nim";
        reason_973078562 = r_p0;
      framePtr = F.prev;

      
    }

  var result_973078556 = null;

  var F = {procname: "asyncjs_examples_2.main", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
  framePtr = F;
  BeforeRet: {
    F.line = 251;
    F.filename = "asyncjs.nim";
    var reason_973078562 = null;
    F.line = 251;
    (await catch__asyncjs95examples9550_u55(fn__asyncjs95examples9550_u8(6), HEX3Aanonymous__asyncjs95examples9550_u36));
    if (!((reason_973078562 == null))) {
    F.line = 251;
    failedAssertImpl__stdZassertions_u85(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim(19, 5) `reason == nil` "));
    }
    
    F.line = 251;
    (await catch__asyncjs95examples9550_u55(fn__asyncjs95examples9550_u8(7), HEX3Aanonymous__asyncjs95examples9550_u74));
    if (!(!((reason_973078562 == null)))) {
    F.line = 251;
    failedAssertImpl__stdZassertions_u85(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim(21, 5) `reason != nil` "));
    }
    
    if (!(contains__pureZstrutils_u1811(cstrToNimstr(reason_973078562.message), [102,111,111,98,97,114,58,32,55]))) {
    F.line = 251;
    failedAssertImpl__stdZassertions_u85(makeNimstrLit("/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim(22, 5) `\"foobar: 7\" in $reason.message` "));
    }
    
    F.line = 251;
    result_973078556 = undefined;
    break BeforeRet;
  };
  framePtr = F.prev;

  return result_973078556;

}
var F = {procname: "module asyncjs_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
framePtr = F;
F.line = 251;
F.filename = "asyncjs.nim";
var _ = main__asyncjs95examples9550_u26();
framePtr = F.prev;
var F = {procname: "module asyncjs_examples_2", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_examples_2.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
var F = {procname: "module asyncjs_group0_examples", prev: framePtr, filename: "/home/runner/work/Nim/Nim/doc/html/nimcache/runnableExamples/asyncjs_group0_examples.nim", line: 0};
framePtr = F;
framePtr = F.prev;
